export const GET_NEW_FAVORITE = 'GET_NEW_FAVORITE' //ADD_FAVORITE

export const ADD_DATA_FAVORITE = 'ADD_DATA_FAVORITE'

export const CLICK_ON_CART = 'CLICK_ON_CART'

export const GET_DATA = 'GET_DATA_LIST'

export const REQUEST = 'REQUEST'

